#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
# 
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#


name: Build OpenCore-Mod

on:
  push:
  schedule:
    - cron: '* */6 * * *'
  workflow_dispatch:

env:
  PROJECT_TYPE: UEFI
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
  WERROR: 1

jobs:
  build-macos:
    name: macOS XCODE5
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v3

      - name: Add Linux Toolchain
        run: brew tap FiloSottile/homebrew-musl-cross

      - name: Install Linux Toolchain
        run: brew install musl-cross
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_NO_AUTO_UPDATE: 1

      - name: Install Dependencies
        run: brew install openssl mingw-w64 nasm
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_NO_AUTO_UPDATE: 1

      - name: Install Dependencies
        run: brew install openssl mingw-w64 nasm
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_NO_AUTO_UPDATE: 1

      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1
          git clone https://gitee.com/btwise/OpenCore_NO_ACPI.git OpenCore_NO_ACPI
          
          ocversion=$(grep OPEN_CORE_VERSION OpenCore_NO_ACPI/Include/Acidanthera/Library/OcMainLib.h | sed 's/.*"\(.*\)".*/\1/' | grep -E '^[0-9.]+$')
          pushd ./OpenCore_NO_ACPI && commitver=$(git rev-parse --short HEAD) && popd
          latesttag=$(wget -qO- -t1 -T2 "https://api.github.com/repos/wjz304/OpenCore_NO_ACPI_Build/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')

          echo ocversion: $ocversion
          echo commitver: $commitver
          echo latesttag: $latesttag

          if [ "${ocversion}_${commitver}" == "${latesttag}" ]; then
              echo "isNew=false" >> $GITHUB_ENV
          else
              echo "isNew=true" >> $GITHUB_ENV
              echo "ocversion=${ocversion}" >> $GITHUB_ENV
              echo "commitver=${commitver}" >> $GITHUB_ENV
              echo "latesttag=${latesttag}" >> $GITHUB_ENV
          fi
      
      - name: build Duet
        if: env.isNew == 'true'
        run: cd OpenCore_NO_ACPI && ./build_duet.tool

      - name: build OC
        if: env.isNew == 'true'
        run: cd OpenCore_NO_ACPI && ./build_oc.tool

      - name: Upload to Artifacts
        if: env.isNew == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: macOS XCODE5 Artifacts
          path: OpenCore_NO_ACPI/Binaries/*.zip

      - name: Upload to Release
        if: env.isNew == 'true'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OpenCore_NO_ACPI/Binaries/*.zip
          tag: ${{ env.ocver }}_${{ env.commitver }}
          file_glob: true
