#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
# 
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#


name: Build OpenCore-Mod

on:
  workflow_dispatch:
    inputs:
      welcome:
        description: 'Welcome (bottom left)'
        required: true
        default: 'Welcome To Use  MOD-OC'


      custom:
        description: 'Custom (bottom right)'
        required: true
        default: ''


env:
  PROJECT_TYPE: UEFI
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
  WERROR: 1

jobs:
  build-macos:
    name: macOS XCODE5
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v3

      - name: Add Linux Toolchain
        run: brew tap FiloSottile/homebrew-musl-cross

      - name: Install Linux Toolchain
        run: brew install musl-cross
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_NO_AUTO_UPDATE: 1

      - name: Install Dependencies
        run: brew install openssl mingw-w64 nasm jq
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_NO_AUTO_UPDATE: 1

      - name: CI Bootstrap
        run: |
          git clone https://gitee.com/btwise/OpenCore_NO_ACPI.git OpenCore_NO_ACPI
          cd ./OpenCore_NO_ACPI
          
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

          sed -i'.bak' "s#Welcome To Use  MOD-OC#${{ inputs.welcome }}#g; s#MOD By BTWISE | WeChat:15242609 QQ:15242609#${{ inputs.custom }}#g" ./Library/OcMainLib/OpenCoreMisc.c

          
      - name: build Duet
        run: cd OpenCore_NO_ACPI && ./build_duet.tool

      - name: build OC
        run: cd OpenCore_NO_ACPI && ./build_oc.tool

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OpenCore-Mod Custom
          path: OpenCore_NO_ACPI/Binaries/*.zip


